# Generated by Django 5.1.7 on 2025-03-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rock',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rock',
            name='lon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rock',
            name='num_holes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
